# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: newenar
# "service" is the name of this project. This will also be added to your AWS resource names.
service: notification-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
    PENDING_MESSAGES_QUEUE:
      Ref: PendingMessages
    PENDING_MESSAGES_QUEUE_NAME: PendingMessages
    EMAIL_SOURCE: ${ssm:/notification-api/email-source}
    DESTINATION_EMAIL: ${ssm:/notification-api/destination-email}
    CLOUDFRONT_DOMAIN: ${ssm:/notification-api/cloudfront-domain}

  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "sqs:SendMessage"
    Resource: "arn:aws:sqs:${self:provider.region}:${aws:accountId}:${self:provider.environment.PENDING_MESSAGES_QUEUE_NAME}"
  - Effect: "Allow"
    Action:
      - "ses:SendEmail"
      - "ses:SendRawEmail"
    Resource: "*"
  - Effect: "Allow"
    Action:
      - "ssm:GetParameter"
    Resource: "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/notification-api/*"
  - Effect: "Allow"
    Action:
      - "dynamodb:GetItem"
      - "dynamodb:PutItem"
      - "dynamodb:UpdateItem"
    Resource: "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/email-rate-limit}"

functions:
  validateOrigin:
    handler: endpoints/authorizer.handler

  reciveMessage:
    handler: endpoints/receiveMessage.handler
    events:
      - http:
          path: message
          method: post
          authorizer:
            name: validateOrigin
            type: request
            identitySource: method.request.header.Origin
          cors: true
  sendEmail:
    handler: handler1.sendEmail
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PendingMessages
              - Arn
          batchSize: 1

resources:
  Resources:
    PendingMessages:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.environment.PENDING_MESSAGES_QUEUE_NAME}
    
    EmailRateLimitTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "email-rate-limit"
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: rateLimitKey
            AttributeType: S
        KeySchema:
          - AttributeName: rateLimitKey
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true
