# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sanit
# "service" is the name of this project. This will also be added to your AWS resource names.
service: notification-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
    PENDING_MESSAGES_QUEUE:
      Ref: PendingMessages
    PENDING_MESSAGES_QUEUE_NAME: PendingMessages
    EMAIL_SOURCE: "xxxxxxxx@gmail.com" # Cambia esto por tu dirección de correo verificada en SES
    DESTINATION_EMAIL: "xxxxxxxx@gmail.com" # Cambia esto por tu dirección de correo destino

  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "sqs:SendMessage"
    Resource: "arn:aws:sqs:${self:provider.region}:${aws:accountId}:${self:provider.environment.PENDING_MESSAGES_QUEUE_NAME}"
  - Effect: "Allow"
    Action:
      - "ses:SendEmail"
      - "ses:SendRawEmail"
    Resource: "*"

functions:
  reciveMessage:
    handler: handler1.reciveMessage
    events:
      - httpApi:
          path: /recive
          method: post
  sendEmail:
    handler: handler1.sendEmail
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PendingMessages
              - Arn
          batchSize: 1

resources:
  Resources:
    PendingMessages:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.environment.PENDING_MESSAGES_QUEUE_NAME}
